# -*- coding: utf-8 -*-
"""FirstAssignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b6adOq_4ELq9hl9IHisAzFTYXVgdoEMk
"""

import hashlib
import string
target ='0000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'

entry = input("Enter your value: ") 
print(entry)

a= 1
while(True):
  append_string = entry + a.__str__()
  result = hashlib.sha256(append_string.encode())
  final = result.hexdigest().upper()
  if(final < target):
     break
  else :
    a = a + 1

print(a)

'''
append_string = entry + a.__str__()
result = hashlib.sha256(append_string.encode())
final = result.hexdigest().upper()
final
'''